### ISSUE TITLE
为什么不直接用高斯函数作为基函数？

### ISSUE THREAD

**Issue by XuLinFeng569212510** [haojiubujian0/Poisson-surface-reconstruction#1]
感谢提供的代码，第一次看泊松重建，有挺多问题不解的，想请教一些问题，1、代码中使用的是分段多项式去拟合一个近似高斯函数，那为何不直接用高斯函数作为基函数呢？2、magic_cube.cpp这里面的操作有相关的论文资料可以参考吗？3、另外magic_cube.cpp这里面的第72行，第113行的dir在for循环是否应该<3,不然switch那里不可能等于2吧？，谢谢！

**Comment by haojiubujian0** [comment]
好的，非常欢迎你的提问。下面是针对你所提出的几个问题的一些具体解释：   

1. 对于问题1，其实在作者发布的06年的泊松表面重建论文中已经提到了这一点：如果直接使用高斯函数，会使得计算量较大。另外，还可以这样理解，使用多项式函数去拟合不仅容易实现，而且计算量较小；对于一些函数的操作，比如求导、函数相乘之类的，采用多项式总是很容易实现的。
2. 对于问题2，magic_cube.cpp实现的其实是一个和魔方（日常生活中的那种魔方，一个魔方有27个节点）类似的数据结构，这个结构主要是用来计算点云数据的权重分布等功能的。对于一个点云数据（三维坐标）以及对于一个给定的八叉树深度，我们可以在这个深度上构建以该点云数据为中心的魔方（也就是说，使得这个点云数据位于魔方的中心节点），构建完这个结构后，就可以计算这个点云数据分别对这27个节点的权重分布。
3. 对于问题3，我翻看了一下代码，我这里是错误的，谢谢你的指正。

**Comment by XuLinFeng569212510** [comment]
另外，在octree.h里面的第611行，这句gaussian_appro.scale(curr_width);是不是没有起作用，因为并没有一个对象接受返回的输出？

**Comment by haojiubujian0** [comment]
不好意思，最近有点忙，抽不出什么时间。确实是的，octree.h的611行有bug。我刚检查了一下代码，这一步是需要对当前的滤波器函数进行缩放的，因此可以直接在前一句，也就是610行中进行缩放即可。
